<div class='panel-heading'><{$content_header|default:false}></div>
<div class='panel-body'>
	<div class='col-sm-3'><{$smarty.const._MA_MYMODULE_TESTFIELD_TEXT}>: </div>
	<div class='col-sm-8'><{$testfield.text}></div>
	<div class='col-sm-3'><{$smarty.const._MA_MYMODULE_TESTFIELD_TEXTAREA}>: </div>
	<div class='col-sm-8'><{$testfield.textarea}></div>
	<div class='col-sm-3'><{$smarty.const._MA_MYMODULE_TESTFIELD_DHTML}>: </div>
	<div class='col-sm-8'><{$testfield.dhtml}></div>
	<div class='col-sm-3'><{$smarty.const._MA_MYMODULE_TESTFIELD_CHECKBOX}>: </div>
	<div class='col-sm-8'><{$testfield.checkbox}></div>
	<div class='col-sm-3'><{$smarty.const._MA_MYMODULE_TESTFIELD_YESNO}>: </div>
	<div class='col-sm-8'><{$testfield.yesno}></div>
	<div class='col-sm-3'><{$smarty.const._MA_MYMODULE_TESTFIELD_SELECTBOX}>: </div>
	<div class='col-sm-8'><{$testfield.selectbox}></div>
	<div class='col-sm-3'><{$smarty.const._MA_MYMODULE_TESTFIELD_USER}>: </div>
	<div class='col-sm-8'><{$testfield.user}></div>
	<div class='col-sm-3'><{$smarty.const._MA_MYMODULE_TESTFIELD_COLOR}>: </div>
	<div class='col-sm-8'><{$testfield.color}></div>
	<div class='col-sm-3'><{$smarty.const._MA_MYMODULE_TESTFIELD_IMAGELIST}>: </div>
	<div class='col-sm-8'><img src='<{$xoops_icons32_url|default:false}>/<{$testfield.imagelist}>' alt='testfields' ></div>
	<div class='col-sm-3'><{$smarty.const._MA_MYMODULE_TESTFIELD_URLFILE}>: </div>
	<div class='col-sm-8'><{$testfield.urlfile}></div>
	<div class='col-sm-3'><{$smarty.const._MA_MYMODULE_TESTFIELD_UPLIMAGE}>: </div>
	<div class='col-sm-9'><img src='<{$mymodule_upload_url|default:false}>/images/testfields/<{$testfield.uplimage}>' alt='testfields' ></div>
	<div class='col-sm-3'><{$smarty.const._MA_MYMODULE_TESTFIELD_UPLFILE}>: </div>
	<div class='col-sm-8'><{$testfield.uplfile}></div>
	<div class='col-sm-3'><{$smarty.const._MA_MYMODULE_TESTFIELD_TEXTDATESELECT}>: </div>
	<div class='col-sm-8'><{$testfield.textdateselect}></div>
	<div class='col-sm-3'><{$smarty.const._MA_MYMODULE_TESTFIELD_SELECTFILE}>: </div>
	<div class='col-sm-8'><{$testfield.selectfile}></div>
	<div class='col-sm-3'><{$smarty.const._MA_MYMODULE_TESTFIELD_COUNTRY_LIST}>: </div>
	<div class='col-sm-8'><{$testfield.country_list}></div>
	<div class='col-sm-3'><{$smarty.const._MA_MYMODULE_TESTFIELD_RADIO}>: </div>
	<div class='col-sm-8'><{$testfield.radio}></div>
	<div class='col-sm-3'><{$smarty.const._MA_MYMODULE_TESTFIELD_STATUS}>: </div>
	<div class='col-sm-8'><{$testfield.status}></div>
	<div class='col-sm-3'><{$smarty.const._MA_MYMODULE_TESTFIELD_DATETIME}>: </div>
	<div class='col-sm-8'><{$testfield.datetime}></div>
	<div class='col-sm-3'><{$smarty.const._MA_MYMODULE_TESTFIELD_COMBOBOX}>: </div>
	<div class='col-sm-8'><{$testfield.combobox}></div>
	<div class='col-sm-3'><{$smarty.const._MA_MYMODULE_TESTFIELD_RATINGS}>: </div>
	<div class='col-sm-8'><{$testfield.ratings}></div>
</div>
